version: "3.9"

services:
  extralimpo-site:
    build:
      context: .
      dockerfile: Dockerfile
    image: extralimpo-site:latest
    container_name: extralimpo-site
    ports:
      - "5467:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - nginx_logs:/var/log/nginx
    environment:
      - TZ=America/Recife
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - web

  # Opcional: Serviço para monitorar logs
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    depends_on:
      - extralimpo-site
    command:
      - -nginx.scrape-uri=http://extralimpo-site:80/stub_status
    restart: unless-stopped
    networks:
      - web

volumes:
  nginx_logs:
    driver: local

networks:
  web:
    driver: bridge
